config/routes.rb
Depot::Application.routes.draw do
  resources :payment_types

  resources :orders

  resources :line_items do
    put 'decrement', on: :member
  end

  resources :carts

  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'
  

  

end

app/controllers/payment_types_controller.rb
class PaymentTypesController < ApplicationController
  before_action :set_payment_type, only: [:show, :edit, :update, :destroy]

  # GET /payment_types
  # GET /payment_types.json
  def index
    @payment_types = PaymentType.all
  end

  # GET /payment_types/1
  # GET /payment_types/1.json
  def show
  end

  # GET /payment_types/new
  def new
    @payment_type = PaymentType.new
  end

  # GET /payment_types/1/edit
  def edit
  end

  # POST /payment_types
  # POST /payment_types.json
  def create
    @payment_type = PaymentType.new(payment_type_params)

    respond_to do |format|
      if @payment_type.save
        format.html { redirect_to @payment_type, notice: 'Payment type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_types/1
  # PATCH/PUT /payment_types/1.json
  def update
    respond_to do |format|
      if @payment_type.update(payment_type_params)
        format.html { redirect_to @payment_type, notice: 'Payment type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_types/1
  # DELETE /payment_types/1.json
  def destroy
    @payment_type.destroy
    respond_to do |format|
      format.html { redirect_to payment_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_type
      @payment_type = PaymentType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_type_params
      params.require(:payment_type).permit(:name)
    end
end

app/views/payment_types/_form.html.erb
<%= form_for(@payment_type) do |f| %>
  <% if @payment_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_type.errors.count, "error") %> prohibited this payment_type from being saved:</h2>

      <ul>
      <% @payment_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_types/edit.html.erb
<h1>Editing payment_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_type %> |
<%= link_to 'Back', payment_types_path %>

app/views/payment_types/index.html.erb
<h1>Listing payment_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @payment_types.each do |payment_type| %>
      <tr>
        <td><%= payment_type.name %></td>
        <td>
          <%= link_to 'Show', payment_type %> | 
          <%= link_to 'Edit', edit_payment_type_path(payment_type) %> | 
          <%= link_to 'Destroy', payment_type, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment type', new_payment_type_path %>

app/views/payment_types/new.html.erb
<h1>New payment_type</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_types_path %>

app/views/payment_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @payment_type.name %>
</p>

<%= link_to 'Edit', edit_payment_type_path(@payment_type) %> |
<%= link_to 'Back', payment_types_path %>